--https://school.programmers.co.kr/learn/courses/30/lessons/151139
-- 서브쿼리, 2중 GROUP BY
SELECT MONTH(START_DATE) "MONTH", CAR_ID , COUNT(HiSTORY_ID) "RECORDS"
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE CAR_ID IN (SELECT CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    WHERE START_DATE BETWEEN "2022-08-01" AND "2022-10-31"
                    GROUP BY CAR_ID
                    HAVING COUNT(HISTORY_ID) >= 5)
                    AND START_DATE BETWEEN "2022-08-01" AND "2022-10-31"
    GROUP BY MONTH(START_DATE), CAR_ID
    ORDER BY MONTH(START_DATE) ASC, CAR_ID DESC;