--https://school.programmers.co.kr/learn/courses/30/lessons/133026

SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) "TOTAL_ORDER"
    FROM FIRST_HALF FH
    INNER JOIN ICECREAM_INFO II
    ON FH.FLAVOR = II.FLAVOR
    GROUP BY INGREDIENT_TYPE
    ORDER BY SUM(TOTAL_ORDER) ASC;