--https://school.programmers.co.kr/learn/courses/30/lessons/164670
-- 서브쿼리 활용


SELECT B.USER_ID, B.NICKNAME, CONCAT(B.CITY,' ',B.STREET_ADDRESS1,' ',B.STREET_ADDRESS2) "전체주소",CONCAT(SUBSTR(B.TLNO,1,3),'-',SUBSTR(B.TLNO,4,4),'-',SUBSTR(B.TLNO,8,4)) "전화번호"
    FROM (SELECT WRITER_ID, COUNT(BOARD_ID) 
            FROM USED_GOODS_BOARD 
            GROUP BY WRITER_ID
            HAVING COUNT(BOARD_ID) >= 3) A
    INNER JOIN USED_GOODS_USER B
    ON A.WRITER_ID = B.USER_ID
    ORDER BY B.USER_ID DESC;