--https://school.programmers.co.kr/learn/courses/30/lessons/131533
-- GROUP BY - SUM 활용

SELECT P.PRODUCT_CODE, SUM(PRICE*SALES_AMOUNT) "SALES"
    FROM PRODUCT P
    INNER JOIN OFFLINE_SALE OS
    ON P.PRODUCT_ID = OS.PRODUCT_ID
    GROUP BY P.PRODUCT_CODE
    ORDER BY SUM(PRICE*SALES_AMOUNT) DESC, PRODUCT_CODE ASC;