--https://school.programmers.co.kr/learn/courses/30/lessons/164668

SELECT UGU.USER_ID, UGU.NICKNAME, SUM(PRICE) "TOTAL_SALES"
    FROM USED_GOODS_BOARD UGB
    INNER JOIN USED_GOODS_USER UGU
    ON UGB.WRITER_ID = UGU.USER_ID
    WHERE UGB.STATUS = 'DONE'
    GROUP BY UGB.WRITER_ID
    HAVING SUM(PRICE) >= 700000
    ORDER BY SUM(PRICE) ASC;