--https://school.programmers.co.kr/learn/courses/30/lessons/131117
-- 총 매출액 SUM(가격*갯수)

SELECT A.PRODUCT_ID, A.PRODUCT_NAME, SUM(A.PRICE*B.AMOUNT) "TOTAL_SALES"
    FROM FOOD_PRODUCT A
    INNER JOIN FOOD_ORDER B
    ON A.PRODUCT_ID = B.PRODUCT_ID
    WHERE PRODUCE_DATE LIKE '2022-05%'
    GROUP BY A.PRODUCT_ID
    ORDER BY SUM(A.PRICE*B.AMOUNT) DESC, A.PRODUCT_ID ASC;