--https://school.programmers.co.kr/learn/courses/30/lessons/131118
-- REGEXP (A|B)

SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE,	A.FAVORITES, A.ADDRESS, ROUND(AVG(B.REVIEW_SCORE),2) "SCORE"
    FROM REST_INFO A
    INNER JOIN REST_REVIEW B
    ON A.REST_ID = B.REST_ID
    WHERE A.ADDRESS REGEXP ('^서울특별시|^서울시')
    # WHERE A.ADDRESS REGEXP ('서울특별시|서울시')
    GROUP BY A.REST_ID
    ORDER BY AVG(B.REVIEW_SCORE) DESC, A.FAVORITES DESC;