--https://school.programmers.co.kr/learn/courses/30/lessons/131123
-- WHERE 컬럼1, 컬럼2 IN (SELECT 컬럼1,컬럼2 FROM~)
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
    FROM REST_INFO
    WHERE (FOOD_TYPE,FAVORITES) IN 
        (SELECT FOOD_TYPE, MAX(FAVORITES) FROM REST_INFO GROUP BY FOOD_TYPE)
    ORDER BY FOOD_TYPE DESC;