--https://school.programmers.co.kr/learn/courses/30/lessons/157342
-- DATEDIFF(), AVG-GROUP BY-HAVING, ROUND() 활용

SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE,START_DATE)+1),1) "AVERAGE_DURATION"
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
    HAVING ROUND(AVG(DATEDIFF(END_DATE,START_DATE)+1),1) >= 7
    ORDER BY ROUND(AVG(DATEDIFF(END_DATE,START_DATE)+1),1) DESC, CAR_ID DESC;